services:
  catalogue:
    build: ./catalogue
    image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user: 
    build: ./user
    image: user:1.0.0
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./cart
    image: cart:1.0.0
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  payment:
    build: ./payment
    image: payment:1.0.0
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    build: ./frontend
    image: frontend:1.0.0
    container_name: frontend
    ports:
    - 80:80 
    depends_on:
    - catalogue
    - user  
    - cart
    - shipping
    - payment
  mongodb:
    build: ./mongodb
    image: mongodb:1.0.0 # docker build -t mongodb:1.0.0
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis: 
    build: ./redis
    image: redis:1.0.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: mysql:1.0.0
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    build: ./rabbitmq
    image: rabbitmq:1.0.0
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq      


networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:    
